
# Import Dependencies

In [1]:

import os
import numpy as np
import pandas as pd


## Import CSV's

In [5]:


file_path = os.path.join("Resources", "Exotic -Greenhouse Frog.csv")
frogs_df = pd.read_csv(file_path)

frogs_df.head()

,Specimen Number,Species ID,Group,Family,Scientific Name,Common Name,Country,State,County,Locality,...,Title 5,Publisher 5,Location 5,Reference 6,Type 6,Date 6,Author 6,Title 6,Publisher 6,Location 6
0,156016,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,NaN,state non-specific,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,753385,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,753386,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,753387,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,753388,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:

file_path = os.path.join("Resources", "Exotic - Zebra Mussels.csv")
zebras_df = pd.read_csv(file_path)

zebras_df.head()

,Specimen Number,Species ID,Group,Family,Scientific Name,Common Name,Country,State,County,Locality,...,Title 5,Publisher 5,Location 5,Reference 6,Type 6,Date 6,Author 6,Title 6,Publisher 6,Location 6
0,615085,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,NaN,"Lake Winnipeg, at Winnipeg Beach, Manitoba, Ca...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,615297,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,NaN,"Lake Winnipeg, at Gimli Harbour, Manitoba, Canada",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,615300,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,NaN,"Lake Winnipeg, at Willow Point, Manitoba, Canada",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,615301,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,NaN,"Lake Winnipeg, at Silver Harbour, Manitoba, Ca...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,615302,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,NaN,"Lake Winnipeg, at Balsam Bay Harbour, Manitoba...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


### Structure Data


### Combine Data


### NULL's and shit