
# Import Dependencies

In [77]:

import os
import numpy as np
import pandas as pd


## Import CSV's

In [78]:


file_path = os.path.join("Resources", "Exotic -Greenhouse Frog.csv")
frogs_df = pd.read_csv(file_path)

frogs_df.head()

,Specimen Number,Species ID,Group,Family,Scientific Name,Common Name,Country,State,County,Locality,...,Title 5,Publisher 5,Location 5,Reference 6,Type 6,Date 6,Author 6,Title 6,Publisher 6,Location 6
0,156016,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,NaN,state non-specific,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,753385,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,753386,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,753387,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,753388,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:

file_path = os.path.join("Resources", "Exotic - Zebra Mussels.csv")
zebras_df = pd.read_csv(file_path)

zebras_df[["Month", "Day", "Year"]]

      Month   Day  Year
0      10.0  17.0  2013
1      10.0  11.0  2013
2      10.0   NaN  2013
3      10.0   NaN  2013
4      10.0   NaN  2013
...     ...   ...   ...
7925    NaN   NaN  1998
7926    NaN   NaN  1998
7927    NaN   NaN  1999
7928   10.0   5.0  2005
7929   10.0  19.0  2010

[7930 rows x 3 columns]


### Structure Data

In [84]:
wanted_columns = ["Specimen Number", "Species ID", "Group", "Family", "Scientific Name", "Common Name", "Country", "State", "County", "Locality", "Latitude", "Longitude", "Drainage Name", "Year", "Month", "Day"]
zebras_df = zebras_df[wanted_columns]
zebras_df.head()

,Specimen Number,Species ID,Group,Family,Scientific Name,Common Name,Country,State,County,Locality,Latitude,Longitude,Drainage Name,Year,Month,Day
0,615085,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Winnipeg Beach, Manitoba, Ca...",50.50821,-96.96738,1,2013,10.0,17.0
1,615297,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Gimli Harbour, Manitoba, Canada",50.63182,-96.98356,1,2013,10.0,11.0
2,615300,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Willow Point, Manitoba, Canada",50.60386,-96.95781,1,2013,10.0,1.0
3,615301,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Silver Harbour, Manitoba, Ca...",50.81161,-96.96326,1,2013,10.0,1.0
4,615302,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Balsam Bay Harbour, Manitoba...",50.47381,-96.58357,1,2013,10.0,1.0

In [83]:
zebras_df = zebras_df.fillna(1)
zebras_df.head()

,Specimen Number,Species ID,Group,Family,Scientific Name,Common Name,Country,State,County,Locality,Latitude,Longitude,Drainage Name,Year,Month,Day
0,615085,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Winnipeg Beach, Manitoba, Ca...",50.50821,-96.96738,1,2013,10.0,17.0
1,615297,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Gimli Harbour, Manitoba, Canada",50.63182,-96.98356,1,2013,10.0,11.0
2,615300,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Willow Point, Manitoba, Canada",50.60386,-96.95781,1,2013,10.0,1.0
3,615301,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Silver Harbour, Manitoba, Ca...",50.81161,-96.96326,1,2013,10.0,1.0
4,615302,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Balsam Bay Harbour, Manitoba...",50.47381,-96.58357,1,2013,10.0,1.0

In [87]:
zebras_df['Recorded Date'] = zebras_df.Month.astype(str) + zebras_df.Day.astype(str) + zebras_df.Year.astype(str)
zebras_df.head()

,Specimen Number,Species ID,Group,Family,Scientific Name,Common Name,Country,State,County,Locality,Latitude,Longitude,Drainage Name,Year,Month,Day,Recorded Date
0,615085,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Winnipeg Beach, Manitoba, Ca...",50.50821,-96.96738,1,2013,10.0,17.0,10.017.02013
1,615297,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Gimli Harbour, Manitoba, Canada",50.63182,-96.98356,1,2013,10.0,11.0,10.011.02013
2,615300,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Willow Point, Manitoba, Canada",50.60386,-96.95781,1,2013,10.0,1.0,10.01.02013
3,615301,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Silver Harbour, Manitoba, Ca...",50.81161,-96.96326,1,2013,10.0,1.0,10.01.02013
4,615302,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Balsam Bay Harbour, Manitoba...",50.47381,-96.58357,1,2013,10.0,1.0,10.01.02013

In [93]:
zebras_df.drop(['Year', 'Month', 'Day'], axis='columns', inplace=True)

In [94]:
zebras_df

,Specimen Number,Species ID,Group,Family,Scientific Name,Common Name,Country,State,County,Locality,Latitude,Longitude,Drainage Name,Recorded Date
0,615085,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Winnipeg Beach, Manitoba, Ca...",50.508210,-96.967380,1,10.017.02013
1,615297,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Gimli Harbour, Manitoba, Canada",50.631820,-96.983560,1,10.011.02013
2,615300,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Willow Point, Manitoba, Canada",50.603860,-96.957810,1,10.01.02013
3,615301,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Silver Harbour, Manitoba, Ca...",50.811610,-96.963260,1,10.01.02013
4,615302,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Balsam Bay Harbour, Manitoba...",50.473810,-96.583570,1,10.01.02013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7925,118181,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,United States of America,WV,Wood,Ohio River (R.M. 205) [just below Belleville L...,39.105370,-81.740356,Upper Ohio-Shade,1.01.01998
7926,118184,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,United States of America,WV,Wood,Ohio River (R.M. 176) at Muskingum Island at B...,39.377380,-81.491425,Upper Ohio-Shade,1.01.01998
7927,118438,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,United States of America,WV,Wood,Ohio River (R.M. 175.2) about 3 miles downrive...,39.380695,-81.489883,Upper Ohio-Shade,1.01.01999
7928,541415,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,United States of America,WV,Wood,"Ohio River at RM 205.2, ORSANCO survey site OH...",39.099000,-81.741470,Upper Ohio-Shade,10.05.02005
7929,541258,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,United States of America,WV,Wood,"Ohio River at RM 204.4, ORSANCO survey site OH...",39.111720,-81.737920,Upper Ohio-Shade,10.019.02010

In [96]:
wanted_columns = ["Specimen Number", "Species ID", "Group", "Family", "Scientific Name", "Common Name", "Country", "State", "County", "Locality", "Latitude", "Longitude", "Drainage Name", "Year", "Month", "Day"]
frogs_df = frogs_df[wanted_columns]
frogs_df.head()

,Specimen Number,Species ID,Group,Family,Scientific Name,Common Name,Country,State,County,Locality,Latitude,Longitude,Drainage Name,Year,Month,Day
0,156016,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,NaN,state non-specific,32.79157,-86.82763,South Atlantic-Gulf Region,1991,NaN,NaN
1,753385,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,2012,3.0,13.0
2,753386,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,2012,3.0,14.0
3,753387,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,2012,3.0,15.0
4,753388,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,2012,5.0,8.0

In [98]:
frogs_df = frogs_df.fillna(1)
frogs_df.head()

,Specimen Number,Species ID,Group,Family,Scientific Name,Common Name,Country,State,County,Locality,Latitude,Longitude,Drainage Name,Year,Month,Day
0,156016,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,1,state non-specific,32.79157,-86.82763,South Atlantic-Gulf Region,1991,1.0,1.0
1,753385,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,2012,3.0,13.0
2,753386,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,2012,3.0,14.0
3,753387,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,2012,3.0,15.0
4,753388,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,2012,5.0,8.0

In [100]:
frogs_df['Recorded Date'] = frogs_df.Month.astype(str) + frogs_df.Day.astype(str) + frogs_df.Year.astype(str)
frogs_df.head()

,Specimen Number,Species ID,Group,Family,Scientific Name,Common Name,Country,State,County,Locality,Latitude,Longitude,Drainage Name,Year,Month,Day,Recorded Date
0,156016,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,1,state non-specific,32.79157,-86.82763,South Atlantic-Gulf Region,1991,1.0,1.0,1.01.01991
1,753385,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,2012,3.0,13.0,3.013.02012
2,753386,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,2012,3.0,14.0,3.014.02012
3,753387,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,2012,3.0,15.0,3.015.02012
4,753388,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,2012,5.0,8.0,5.08.02012

In [101]:
frogs_df.drop(['Year', 'Month', 'Day'], axis='columns', inplace=True)

In [102]:
frogs_df.head()

,Specimen Number,Species ID,Group,Family,Scientific Name,Common Name,Country,State,County,Locality,Latitude,Longitude,Drainage Name,Recorded Date
0,156016,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,1,state non-specific,32.79157,-86.82763,South Atlantic-Gulf Region,1.01.01991
1,753385,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,3.013.02012
2,753386,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,3.014.02012
3,753387,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,3.015.02012
4,753388,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,AL,Baldwin,"Wilkins Creek, headwaters",30.72800,-87.89500,Mobile-Tensaw,5.08.02012


### Combine Data

In [103]:
zebras_frogs = pd.concat([zebras_df, frogs_df], axis=0)
zebras_frogs

,Specimen Number,Species ID,Group,Family,Scientific Name,Common Name,Country,State,County,Locality,Latitude,Longitude,Drainage Name,Recorded Date
0,615085,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Winnipeg Beach, Manitoba, Ca...",50.508210,-96.96738,1,10.017.02013
1,615297,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Gimli Harbour, Manitoba, Canada",50.631820,-96.98356,1,10.011.02013
2,615300,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Willow Point, Manitoba, Canada",50.603860,-96.95781,1,10.01.02013
3,615301,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Silver Harbour, Manitoba, Ca...",50.811610,-96.96326,1,10.01.02013
4,615302,5,Mollusks-Bivalves,Dreissenidae,Dreissena polymorpha,zebra mussel,Canada,Manitoba,1,"Lake Winnipeg, at Balsam Bay Harbour, Manitoba...",50.473810,-96.58357,1,10.01.02013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,155345,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,OK,Tulsa,"Tulsa, at Tulsa Zoo, Tropical Rainforest Building",36.212403,-95.90484,Bird,8.06.02002
715,1321263,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,SC,Charleston,residence near Oak Tree Ln and Old Mill Ln,32.824000,-79.82251,Bulls Bay,9.03.02015
716,1616955,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,SC,Charleston,[No locality description provided],32.800220,-79.75642,Bulls Bay,8.031.02018
717,1474232,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,TX,Harris,"Hazard St. Houston, TX",29.748610,-95.40710,Buffalo-San Jacinto,9.023.02018
718,281087,61,Amphibians-Frogs,Eleutherodactylidae,Eleutherodactylus planirostris,Greenhouse Frog,United States of America,TX,Harris,"Houston, at Cockrell Butterfly Center, inside ...",29.722160,-95.39039,Buffalo-San Jacinto,2.06.02012

In [109]:
zebras_frogs.to_csv('Resources/zebra_frogs.csv')